name: prototype_v2.1
root_body: pelvis_link
end_effectors:
- left_foot_floor
- right_foot_floor
- right_welding_point
mirror_pairs:
  left_hip_pitch_joint: right_hip_pitch_joint
  left_hip_roll_joint: right_hip_roll_joint
  left_hip_yaw_joint: right_hip_yaw_joint
  left_knee_pitch_joint: right_knee_pitch_joint
  left_ankle_pitch_joint: right_ankle_pitch_joint
  left_ankle_roll_joint: right_ankle_roll_joint
  left_shoulder_pitch_joint: right_shoulder_pitch_joint
  left_shoulder_roll_joint: right_shoulder_roll_joint
  left_shoulder_yaw_joint: right_shoulder_yaw_joint
  left_elbow_pitch_joint: right_elbow_pitch_joint
  left_wrist_roll_joint: right_wrist_roll_joint
  left_wrist_yaw_joint: right_wrist_yaw_joint
dt: 0.02
save_dir: keyframes
physics:
  kp: 100.0
  kd: 10.0
  motor_tau_limit: 500.0
  dt: 0.02
ui:
  show_com: true
  show_grid: true
  scene_update_hz: 60.0
  root_pose_gizmo_scale: 0.35
  ik_target_gizmo_scale: 0.18
  auto_scale_gizmos: true
  gizmo_scale_ratio: 1.0
  gizmo_reference_height: 1.28
scene:
  auto_inject_floor: true
  show_floor: true
